version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      napi:
        patterns:
          - napi
          - napi-derive
          - napi-build
  - package-ecosystem: npm
    directory: /bindings/npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 5