/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function computeDelta(oldSnapshot: any, newSnapshot: any): any
export declare class Workspace {
  static open(root: string, optionsJson?: string | undefined | null): Workspace
  get currentSnapshot(): any
  rebuildSnapshot(): any
  listNodes(): any
  listScopes(): any
  findOwner(path: string): any
  explainPath(path: string): any
  health(): any
  watchStart(): void
  watchStop(): void
  watchPoll(): any
  getAffectedScopes(event: any): Array<string>
  close(): void
}
