/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Workspace {
  static open(root: string, optionsJson?: string | undefined | null): Workspace
  get currentSnapshot(): any
  rebuildSnapshot(): any
  listNodes(): any
  listScopes(): any
  findOwner(path: string): any
  explainPath(path: string): any
  health(): any
  watchStart(): void
  watchStop(): void
  watchPoll(): any
  getAffectedScopes(event: any): Array<string>
  close(): void
}

export declare function computeDelta(oldSnapshot: any, newSnapshot: any): any
